config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'events#index'

  resources :events
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
	validates :event_name, :event_description, :date, :time, :location, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to events_path
    else
     render :new, status: :unprocessable_entity
   end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to events_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    redirect_to root_path, status: :see_other
  end

  private
  def event_params
    params.require(:event).permit(:event_name, :event_description, :date, :time, :location)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_with model: event do |form| %>
  <div>
  	<%= form.label :event_name %><br>
  	<%= form.text_field :event_name %>
    <%  event.errors.full_messages_for(:event_name).each do |message| %>
      <div><%= message %></div>
      <% end %>
  </div>

  <div>
  	<%= form.label :event_description %><br>
  	<%= form.text_field :event_description %>
    <%  event.errors.full_messages_for(:event_description).each do |message| %>
      <div><%= message %></div>
      <% end %>
  </div>

  <div>
  	<%= form.label :date %><br>
  	<%= form.text_field :date %>
    <%  event.errors.full_messages_for(:date).each do |message| %>
      <div><%= message %></div>
      <% end %>
  </div>

  <div>
  	<%= form.label :time %><br>
  	<%= form.text_field :time %>
    <%  event.errors.full_messages_for(:time).each do |message| %>
      <div><%= message %></div>
      <% end %>
  </div>

  <div>
  	<%= form.label :location %><br>
  	<%= form.text_field :location %>
    <%  event.errors.full_messages_for(:location).each do |message| %>
      <div><%= message %></div>
      <% end %>
  </div><br>

  <div>
  	<%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= render "form", event: @event %>

app/views/events/index.html.erb
<div>
	<h1>List of Events</h1>
	<%= link_to "New Event", new_event_path %>

	<table>
		<thead>
			<tr>
				<th>Event Name</th>
				<td>&nbsp;</td>
				<th>Event Description</th>
				<td>&nbsp;</td>
				<th>Event Date</th>
				<td>&nbsp;</td>
				<th>Event Time</th>
				<td>&nbsp;</td>
				<th>Event Location</th>
				<td>&nbsp;</td>

				<th colspan="3">Action</th>
			</tr>
		</thead>
		<tbody>
			<% @events.each do |event| %>
			  <tr>
			  	<td><%= event.event_name %></td>
			  	<td>&nbsp;</td>
			  	<td><%= event.event_description %></td>
			  	<td>&nbsp;</td>
			  	<td><%= event.date %></td>
			  	<td>&nbsp;</td>
			  	<td><%= event.time %></td>
			  	<td>&nbsp;</td>
			  	<td><%= event.location %></td>
                <td>&nbsp;</td>

			  	<td><%= link_to "View", event %></td>
			  </tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render "form", event: @event %>

app/views/events/show.html.erb
<h3>Student Details</h3>

  <p><strong>Event Name: <%= @event.event_name %></strong></p>
  <p><strong>Event Description: <%= @event.event_description %></strong></p>
  <p><strong>Event Date: <%= @event.date %></strong></p>
  <p><strong>Event Time: <%= @event.time %></strong></p>
  <p><strong>Event Location: <%= @event.location %></strong></p>
  
  <%= link_to "Back", root_path %>
  <td>&nbsp;</td>
  <%= link_to "Edit", edit_event_path(@event) %>
  <td>&nbsp;</td>
  <td><%= link_to "Delete",event_path(@event), data:{turbo_method: :delete, turbo_confirm: "Are you sure"}%></td>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>